# Generated by Django 3.2 on 2021-04-20 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    serialize=False,
                    to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mandatory', models.BooleanField()),
                ('credit_points', models.SmallIntegerField()),
                ('syllabi', models.CharField(max_length=200)),
                ('avg_load', models.DecimalField(decimal_places=5, max_digits=6)),
                ('avg_rating', models.DecimalField(decimal_places=5, max_digits=6)),
                ('num_of_raters', models.IntegerField()),
                ('num_of_reviewers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, null=True)),
                ('course_load', models.SmallIntegerField()),
                ('likes_num', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
                ('professor', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='homepage.professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Professor_to_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
                ('professor_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='homepage.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_code', models.SmallIntegerField(
                        choices=[(-2, 'None'), (-1, 'Cant'), (0, 'Simu'), (1, 'Before')],
                        default=-2)),
                ('course_id', models.ForeignKey(
                    db_column='course_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='new_course_id',
                    to='homepage.course')),
                ('req_course_id', models.ForeignKey(
                    db_column='req_course_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='required_course_id',
                    to='homepage.course')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedUserCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.appuser')),
            ],
        ),
    ]
