# Generated by Django 3.1.7 on 2021-04-12 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              primary_key=True,
                                              serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mandatory', models.BooleanField()),
                ('credit_points', models.SmallIntegerField()),
                ('syllabi', models.CharField(max_length=200)),
                ('avg_load', models.DecimalField(decimal_places=5, max_digits=6)),
                ('avg_rating', models.DecimalField(decimal_places=5, max_digits=6)),
                ('num_of_raters', models.IntegerField()),
                ('num_of_reviewers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.appuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
                ('rate', models.SmallIntegerField()),
                ('course_load', models.SmallIntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor_to_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.course')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='homepage.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_code', models.SmallIntegerField(
                    choices=[(-2, 'None'), (-1, 'Cant'), (0, 'Simu'), (1, 'Before')], default=-2)),
                ('course_id',
                 models.ForeignKey(db_column='course_id',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='new_course_id',
                                   to='homepage.course')),
                ('req_course_id',
                 models.ForeignKey(db_column='req_course_id',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   related_name='required_course_id',
                                   to='homepage.course')),
            ],
        ),
    ]
