# Generated by Django 3.2 on 2021-04-27 14:21

from django.core import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_alter_review_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avg_load',
            field=models.DecimalField(
                decimal_places=5,
                max_digits=6,
                validators=[validators.MinValueValidator(1), validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_rating',
            field=models.DecimalField(
                decimal_places=5,
                max_digits=6,
                validators=[validators.MinValueValidator(1), validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(
                primary_key=True,
                serialize=False,
                validators=[validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_points',
            field=models.SmallIntegerField(
                validators=[validators.MinValueValidator(1), validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_of_raters',
            field=models.IntegerField(
                validators=[validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_of_reviewers',
            field=models.IntegerField(
                validators=[validators.MinValueValidator(0)]),
        ),
    ]
