# Generated by Django 3.2 on 2021-05-04 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_course_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avg_load',
            field=models.DecimalField(blank=True, decimal_places=5,
                                      max_digits=6, null=True,
                                      validators=[
                                          django.core.validators.MinValueValidator(1),
                                          django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=5,
                                      max_digits=6, null=True,
                                      validators=[
                                          django.core.validators.MinValueValidator(1),
                                          django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_of_raters',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_of_reviewers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabi',
            field=models.URLField(blank=True, null=True),
        ),
    ]
